
version: '3.8'

services:
  backend:
    image: avash9857/be-rental_mania
    env_file:
      - ./secrets/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    image: avash9857/fe-rental_mania
    env_file:
      - ./secrets/.env
    ports:
      - "80:80"
    networks:
      - app_network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saibaba9857
      POSTGRES_DB: rentalmania
    ports:
      - "5432:5432"
    volumes:
      - rental_mania-datas:/var/lib/postgresql/data 
    networks:
      - app_network

networks:
  app_network:

volumes:
  rental_mania-data:


  